Integrate the PAKE Extension into the Crypto API specification
ARM-software/psa-api pull request #177
Opened 2024-02-28 10:47 UTC by athoelke

As an initial step for the Crypto API 1.3 release, integrate the API for PAKE operations into the primary specification, now that the PAKE Extension is Final.

Fixes #170.

### Notes on the integration

* Most of the extension forms a new sub-chapter within Cryptographic operations, but the key type and encoding information for SPAKE2+ is integrated into the respective sections.
* Previous indirect references to the Crypto API, have been replaced with direct cross-references. (I hope I didn't miss any)
* I have reworked parts of the Functionality chapter, as multi-part operations are now used with asymmetric cryptography as well.
* Lists of 'key creation functions' all include the `psa_pake_get_shared_key()`.

### Open Issues

1. In the extension, the key export formats, and key derivation procedures for the SPAKE2+ keys are documented as a sub-section of the key type definition (because there was no other logical place for this in the extension spec). This actually seemed very natural, and is arguably a better organisation of this information for readers who are **Users** of the API; than the current Crypto API which aggregates all of the derivation methods in a table under `psa_key_derivation_output_key()`, and formats within a single section, which is more benficial for **Implementers**.

   *Question:* Should we rework this information to follow the PAKE Extension approach and document formats and derivation procedures under each key type? - this seems to also fit better with the addition of additional formats, and production methods for specific key types, that come with #149 and #167.

2024-05-07 18:13 UTC, davidhorstmann-arm requested changes
One nit / wording comment on the functionality section.

I think I also found a [preexisting copypasta](https://github.com/athoelke/psa-api/blob/crypto-1.3-integrate-pake/doc/crypto/api/ops/pake.rst?plain=1#L594) in the PAKE spec:

```rst
    *   Assign the result of the function `psa_pake_cipher_suite_init()` to the object, for example:

        .. code-block:: xref

            psa_pake_operation_t operation;
            operation = psa_pake_operation_init();
```
I believe the `psa_pake_cipher_suite_init()` should be `psa_pake_operation_init()`.

If it's out of scope for this PR I can raise a followup.

Otherwise, the code motion looks good and `psa_pake_get_shared_key()` seems to be listed everywhere that it should.

2024-05-07 18:13 UTC, davidhorstmann-arm commented on doc/crypto/overview/functionality.rst
> +*   One or more *single-part* functions, that carry out one function of that operation. For example, compute, verify, encrypt, or decrypt.
Nit / editorial: I found this wording slightly confusing. Would something like:

```suggestion
*   One or more *single-part* functions, which perform a whole operation in a single function call. For example, compute, verify, encrypt or decrypt.
```
Work as an alternative?

2024-05-08 15:27 UTC, athoelke commented
> I think I also found a [preexisting copypasta](https://github.com/athoelke/psa-api/blob/crypto-1.3-integrate-pake/doc/crypto/api/ops/pake.rst?plain=1#L594) in the PAKE spec:

Well spotted - I have added a commit for this. This is a good PR to fix that error.

2024-05-08 20:04 UTC, athoelke commented on doc/crypto/overview/functionality.rst
>  a sequence of separate steps. This enables fine control over the configuration
I've updated the text along these lines, but keeping consistency with the wording of the setup functions.

I also took the opportunity to add PAKE as an example of why multi-part operations are needed.

2024-05-09 10:56 UTC, merged