Clarify PSA_ALG_ECDSA_ANY policy requirements
ARM-software/psa-api pull request #40
Opened 2022-12-21 11:46 UTC by athoelke

In particular, it does not follow the pattern of `PSA_ALG_RSA_PKCS1V15_SIGN_RAW`

2023-01-06 11:03 UTC, MarcusJGStreets approved these changes

2023-02-20 17:06 UTC, paul-elliott-arm requested changes
1 minor typo.

2023-02-20 17:06 UTC, paul-elliott-arm commented on doc/crypto/api/ops/sign.rst
> +    This value cannot be used to build an algorithm specification to perform an operation. If used in this way, the operation wil fail with an error.
```suggestion
    This value cannot be used to build an algorithm specification to perform an operation. If used in this way, the operation will fail with an error.
```

2023-02-20 22:13 UTC, merged

2025-10-17 17:31 UTC, gilles-peskine-arm commented on doc/crypto/api/ops/sign.rst
> +    This algorithm cannot be used with the wildcard key policy :code:`PSA_ALG_ECDSA(PSA_ALG_ANY_HASH)`. It is only permitted when `PSA_ALG_ECDSA_ANY` is the key's permitted-algorithm policy.
I just noticed this statement. [This isn't how Mbed TLS has always done it](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/533): I considered `PSA_ALG_ECDSA(PSA_ALG_ANY_HASH)` to include `PSA_ALG_ECDSA_ANY`, and `PSA_ALG_RSA_PKCS1V15_SIGN(PSA_ALG_ANY_HASH)` to include `PSA_ALG_RSA_PKCSV15_SIGN_RAW`, even though I [hadn't written it down explicitly](https://github.com/ARMmbed/mbed-crypto/pull/15). So as far as Mbed TLS (and now TF-PSA-Crypto) is concerned, this is an incompatible change in version 1.1 of the API specification.

I'm not going to advocate for a change now, however. It's in the spec so we'll deal with it.